### ISSUE TITLE
Issue while Defining a Custom Role in vSphere for vRealize Automation and vRealize Orchestrator

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#484] opened 2024-01-29 10:39 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.8.0.1048

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

30, 93, 14 | Management | vSphere: Define Custom Roles in vSphere for vRealize Automation and vRealize Orchestrator

Facing issue while defining custom roles in vsphere for vRealize Automation and vRealize Orchestrator

### Error or Debug Output

Error at Script Line 23631 Relevant Command: Set-VIRole -Server $vcfVcenterDetails.fqdn -Role $roleName -AddPrivilege (Get-VIPrivilege -ID $privilege) -Confirm:$False -ErrorAction SilentlyContinue | Out-Null Error Message: Cannot validate argument on parameter 'AddPrivilege'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

### Expected Behavior

Define Custom Roles in vSphere for vRealize Automation and vRealize Orchestrator should work without any issues.

### Actual Behavior

Facing issue while defining custom roles in vsphere for vRealize Automation and vRealize Orchestrator

### Steps to Reproduce

30, 93, 14 | Management | vSphere: Define Custom Roles in vSphere for vRealize Automation and vRealize Orchestrator

**Comment by GaryJBlake** [comment] 2024-02-12 08:08
If we have difference between available role names between VCF 4.x (vSphere 7.x) and VCF  5.x (vSphere 8.x) we will need to create two .role files to handle the correct assignments based on the underlying version of vCenter Server.

**Comment by tenthirtyam** [comment] 2024-02-14 17:18
Self-assigning this one to work with Ian on contributing a fix after we were troubleshooting this same issue in an e2e walkthrough.

The issue is related to privledge changes between vSphere 7 and 8.

**vSphere 7.0:  Profile-driven Storage** [Reference](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-9A79C4A8-8415-433B-A2E9-6A5999E92207.html)

- `StorageProfile.Apply`
- `StorageProfile.EditPermissions`
- `StorageProfile.Update`
- `StorageProfile.View`
- `StorageProfile.ViewPermissions`

**vSphere 8.0 VM Storage Policies** [Reference](https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-security/GUID-9A79C4A8-8415-433B-A2E9-6A5999E92207.html)

- `StorageProfile.Apply`
- `StorageProfile.Update`
- `StorageProfile.View`

**Options:**

- Replace step for Orchestrator with a new function that can simply clone the Administrator role. (Preferred)
- Seperate Role File based on version.

I'll work with Ian on this as it's an opportunity for him to contribute a fix after researching the issue.

**Closed** 2024-02-22 19:38 UTC
Labels: bug, vvs/pca, ci
