### ISSUE TITLE
bug: ERROR Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED

### ISSUE THREAD

**Issue by slakshmanan2706** [vmware/power-validated-solutions-for-cloud-foundation#308] opened 2023-08-02 07:44 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.0

### Module Version

2.6.0.1001

### PowerShell Version

7.3.6

### PowerCLI Version

13.1

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2019

### Description

IAM : 18. vCenter Server: Reconfigure the vSphere Role and Permissions Scope for NSX Manager Service Accounts shows error message for isolated WLD domain.

 

### Error or Debug Output

[ERROR] Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED

### Expected Behavior

should show SUCCESSFUL message

### Actual Behavior

18. vCenter Server: Reconfigure the vSphere Role and Permissions Scope for NSX Manager Service Accounts

Option 18 of IAM shows below error message.

```
 

8/2 12:19:51 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - Selected option = 18
-- | --
8/2 12:19:51 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO -
8/2 12:19:52 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - Version 5.0.9.1022 \| Topology: DualRegion-SingleAZ \| Networking: Public \| Management Domain Tasks: Identity and Access Management
8/2 12:19:52 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO -
8/2 12:19:52 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:21] [...] [NOTE] Starting the Process of Reconfiguring the vSphere Role and Permissions Scope for NSX Manager Service Accounts
8/2 12:19:52 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:21] [...] [INFO] Attempting to Reconfigure the vSphere Role NSX Manager Service Account (svc-sfo-m01-nsx01-sfo-m01-vc01) with (NSX-T Data Center to vSphere Integration) role
8/2 12:19:53 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:24] [...] [INFO] Adding Global Permissions for user (VSPHERE.LOCAL\svc-sfo-m01-nsx01-sfo-m01-vc01) with role (NSX-T Data Center to vSphere Integration) in vCenter Server (sfo-m01-vc01) and vCenter Single Sign-On domain (vsphere.local): SUCCESSFUL
8/2 12:19:53 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:24] [...] [INFO] Attempting to Reconfigure the Access for Service Account (svc-sfo-w01-nsx01-sfo-w01-vc01) with (NoAccess) role
8/2 12:19:53 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:26] [...] [ERROR] Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED
8/2 12:19:53 am | [VisionTestCase.py:74] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:26] [...] [ERROR] Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED
8/2 12:19:54 am | [VisionTestCase.py:74] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:26] [...] [ERROR] Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED
8/2 12:19:54 am | [VisionTestCase.py:74] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:26] [...] [ERROR] Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED
8/2 12:19:54 am | [ConfigUsingPlatformTools.py:114] - [2023-08-02 08:15:26] INFO - [08-02-2023_08:15:26] [...] [NOTE] Finished the Process of Reconfiguring the vSphere Role and Permissions Scope for NSX Manager Service Accounts

 
```

### Steps to Reproduce

1. Deploy VCF 5.0 with WLD in isolated mode.
2. Trigger http://10.158.130.147:8081/view/TB03-PT5/job/L2BAT_SolnEng_VVS_IAM_TB_3A_PT5/ Jenkin and observe the error message.

### Log Fragments and Files

```
[08-02-2023_08:14:56] [...] INFO Attempting to Assign the Enterprise Admin Role to (gg-nsx-enterprise-admins@sfo.rainpole.io)
[08-02-2023_08:14:58] [...] INFO Assigning group (gg-nsx-enterprise-admins@sfo.rainpole.io) the role (enterprise_admin) in NSX for Workload Domain (sfo-m01): SUCCESSFUL
[08-02-2023_08:14:58] [...] INFO Attempting to Assign the Network Admin Role to (gg-nsx-network-admins@sfo.rainpole.io)
[08-02-2023_08:15:01] [...] INFO Assigning group (gg-nsx-network-admins@sfo.rainpole.io) the role (network_engineer) in NSX for Workload Domain (sfo-m01): SUCCESSFUL
[08-02-2023_08:15:01] [...] INFO Attempting to Assign the Auditor Role to (gg-nsx-auditors@sfo.rainpole.io)
[08-02-2023_08:15:02] [...] INFO Assigning group (gg-nsx-auditors@sfo.rainpole.io) the role (auditor) in NSX for Workload Domain (sfo-m01): SUCCESSFUL
[08-02-2023_08:15:02] [...] NOTE Finished the Process of Assigning Active Directory Groups to Roles for NSX Manager
[08-02-2023_08:15:03] [...] NOTE Starting the Process of Creating a Custom Role in vSphere
[08-02-2023_08:15:03] [...] INFO Custom Role Template File Found (nsx-vsphere-integration.role)
[08-02-2023_08:15:03] [...] WAIT Attempting to Create Custom Role (NSX-T Data Center to vSphere Integration) in vSphere Using File (nsx-vsphere-integration.role)
[08-02-2023_08:15:19] [...] INFO Creating a new role in vCenter Server (sfo-m01-vc01.sfo.rainpole.io) named (NSX-T Data Center to vSphere Integration): SUCCESSFUL
[08-02-2023_08:15:19] [...] NOTE Finished the Process of Creating a Custom Role in vSphere
[08-02-2023_08:15:19] [...] NOTE Starting the Process of Assigning NSX Manager Service Account to Single Sign-On Built-In License Administrators Group
[08-02-2023_08:15:19] [...] INFO Attempting to Assign the Single Sign-On License Administrators Role to (svc-sfo-m01-nsx01-sfo-m01-vc01)
[08-02-2023_08:15:21] [...] INFO Assigning SSO Group (LicenseService.Administrators) in vCenter Server (sfo-m01-vc01) to user (svc-sfo-m01-nsx01-sfo-m01-vc01) for domain (vsphere.local): SUCCESSFUL
[08-02-2023_08:15:21] [...] NOTE Finished the Process of Assigning NSX Manager Service Account to Single Sign-On Built-In License Administrators Group
[08-02-2023_08:15:21] [...] NOTE Starting the Process of Reconfiguring the vSphere Role and Permissions Scope for NSX Manager Service Accounts
[08-02-2023_08:15:21] [...] INFO Attempting to Reconfigure the vSphere Role NSX Manager Service Account (svc-sfo-m01-nsx01-sfo-m01-vc01) with (NSX-T Data Center to vSphere Integration) role
[08-02-2023_08:15:24] [...] INFO Adding Global Permissions for user (VSPHERE.LOCAL\svc-sfo-m01-nsx01-sfo-m01-vc01) with role (NSX-T Data Center to vSphere Integration) in vCenter Server (sfo-m01-vc01) and vCenter Single Sign-On domain (vsphere.local): SUCCESSFUL
[08-02-2023_08:15:24] [...] INFO Attempting to Reconfigure the Access for Service Account (svc-sfo-w01-nsx01-sfo-w01-vc01) with (NoAccess) role
[08-02-2023_08:15:26] [...] ERROR Unable to find (svc-sfo-w01-nsx01-sfo-w01-vc01) in vCenter Server (sfo-m01-vc01): PRE_VAILIDATION_FAILED
[08-02-2023_08:15:26] [...] NOTE Finished the Process of Reconfiguring the vSphere Role and Permissions Scope for NSX Manager Service Accounts
```

### Screenshots

svc-sfo-w01-nsx01-sfo-w01-vc01 is available only in WLD VC under (sfo-w01.local).

![image](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/assets/85702650/e51d7275-978f-451d-bece-543ef6246240)

**Comment by GaryJBlake** [comment] 2023-08-03 19:52
This is not a bug with the code but a difference in the process required in the documentation when Isolated Workload domains are used.

Marking as Closed

**Closed by GaryJBlake** 2023-08-03 19:52 UTC
Labels: bug, user-error
