### ISSUE TITLE
issue while Configuring Service Account Permissions for the VMware Aria Automation to VMware NSX Integration.

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#485] opened 2024-01-30 06:32 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1,4.5.2

### Module Version

2.8.0.1048

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

31, 64, 3 | VI Workload Domain | NSX-T Data Center: Configure Service Account Permissions for the vRealize Automation to NSX-T Data Center Integration on the VI Workload Domain NSX Manager Cluster

### Error or Debug Output

[NOTE] Starting the Process of Configuring Service Account Permissions for the VMware Aria Automation to VMware NSX Integration

[INFO] Attempting to Configure Service Account Permissions for (svc-vra-nsx@sfo.rainpole.io) on the VI Workload Domain NSX Manager Cluster

[ERROR] Unable to find user (svc-vra-nsx@sfo.rainpole.io) in Workspace ONE Access for NSX, check user synchronization: PRE_VALIDATION_FAILED

[ERROR] Unable to find user (svc-vra-nsx@sfo.rainpole.io) in Workspace ONE Access for NSX, check user synchronization: PRE_VALIDATION_FAILED

[ERROR] Unable to find user (svc-vra-nsx@sfo.rainpole.io) in Workspace ONE Access for NSX, check user synchronization: PRE_VALIDATION_FAILED

[ERROR] Unable to find user (svc-vra-nsx@sfo.rainpole.io) in Workspace ONE Access for NSX, check user synchronization: PRE_VALIDATION_FAILED

[ERROR] Unable to find user (svc-vra-nsx@sfo.rainpole.io) in Workspace ONE Access for NSX, check user synchronization: PRE_VALIDATION_FAILED

Finished the Process of Configuring Service Account Permissions for the VMware Aria Automation to VMware NSX Integration

### Expected Behavior

 Configure Service Account Permissions for the vRealize Automation to NSX-T Data Center Integration on the VI Workload Domain NSX Manager Cluster should work without any issues

### Actual Behavior

Facing issue while configuring Service Account Permissions for the vRealize Automation to NSX-T Data Center Integration on the VI Workload Domain NSX Manager Cluster

### Steps to Reproduce

31, 64, 3 | VI Workload Domain | NSX-T Data Center: Configure Service Account Permissions for the vRealize Automation to NSX-T Data Center Integration on the VI Workload Domain NSX Manager Cluster

**Comment by GaryJBlake** [comment] 2024-02-07 09:55
Not a bug in `PowerValidatedSolutions`, issue related to function in our internal tool `VMware.PlatformTools` where it had not been updated from the `Add-NsxtVidmRole` cmdlet to `Add-NsxtLdapRole` cmdlet following the removal of Workspace ONE Access from the Identity and Access Management Validated Solution to use only Active Directory over LDAP.

Issue was addressed in `VMware.PlatformTools` and patched on pipeline jumpbox on Jan 12th when the issue was flagged.

**Closed by GaryJBlake** 2024-02-07 09:55 UTC
Labels: bug, declined, ci
