### ISSUE TITLE
Issue while configuring vcf integration with VMware Aria Operations

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#531] opened 2024-03-08 07:59 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.9.0.1029

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Issue while configuring vcf integration with VMware Aria Operations

$adapterDetail.id = (Get-vROPSAdapter | Where-Object {$_.resourceKey.name -eq "$($workloadDomain.name) - vCenter"}).id without any issues

### Error or Debug Output

Configuring the VMware Cloud Foundation Integration in VMware Aria Operations
Error at Script Line 18567
Relevant Command: $adapterDetail.id = (Get-vROPSAdapter | Where-Object {$_.resourceKey.name -eq "$($workloadDomain.name) - vCenter"}).id
Error Message: The property 'id' cannot be found on this object. Verify that the property exists and can be set.

### Expected Behavior

We should get the value for adapterDetail.id without any issues

### Actual Behavior

We are not getting value for adapterDetail.id

### Steps to Reproduce

Issue while configuring vcf integration with VMware Aria Operations

$adapterDetail.id = (Get-vROPSAdapter | Where-Object {$_.resourceKey.name -eq "$($workloadDomain.name) - vCenter"}).id without any issue

**Comment by jshiplett** [comment] 2024-03-13 16:39
Unable to reproduce - just ran through both individual steps and 1-click and both went through without issue.

**Comment by GaryJBlake** [comment] 2024-03-20 10:11
@Ashwini-Ravi closing this issue, it was not possible to reproduce the issue based on Jason's comments when you raised it initially. If you observe the issue again then please re-open sharing more details.

**Closed by GaryJBlake** 2024-03-20 10:11 UTC
Labels: bug, not-reproduced, vvs/iom

**Comment by Ashwini-Ravi** [comment] 2024-03-22 09:50
I am facing this issue again.

 [03-22-2024_09:26:04] [ERROR] System.Management.Automation.CmdletInvocationException: {"message":"Internal Server error, cause unknown.","moreInformation":[{"name":"errorMessage","value":"Permission to perform this operation was denied."}],"httpStatusCode":500,"apiErrorCode":500}
 ---> Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 500 (500).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 [03-22-2024_09:26:04] [ERROR] {"message":"Internal Server error, cause unknown.","moreInformation":[{"name":"errorMessage","value":"Permission to perform this operation was denied."}],"httpStatusCode":500,"apiErrorCode":500}
 [03-22-2024_09:26:04] [ERROR] {"message":"Internal Server error, cause unknown.","moreInformation":[{"name":"errorMessage","value":"Permission to perform this operation was denied."}],"httpStatusCode":500,"apiErrorCode":500}
 [03-22-2024_09:26:04] [ERROR] Response status code does not indicate success: 500 (500).
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
 [03-22-2024_09:26:04] [ERROR] The property 'id' cannot be found on this object. Verify that the property exists and can be set.
