### ISSUE TITLE
Error while provisioning Tanzu Kubernetes cluster

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#301] opened 2023-07-19 11:45 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.0

### Module Version

2.5.0.1008

### PowerShell Version

5.1.14393.5582

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2016

### Description

Error from server (Unable to find a compatible full version hint "1.20"

### Error or Debug Output

Error from server (Unable to find a compatible full version hint "1.20"

### Expected Behavior

The DRI option 16 should run without any issues

### Actual Behavior

We are getting error while running DRI option 16

### Steps to Reproduce

Deploy VCF 5.0 or VCF 451
Configure DRI
Run option 16 in platform tools DRI  tasks

Note: The error is not present in Platform tool log

<img width="1378" alt="Screenshot 2023-07-19 at 4 49 39 PM" src="https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/assets/122252705/05fb934e-d070-4992-8cbc-90ceef8a9e72">

**Comment by jshiplett** [comment] 2023-08-19 19:10
Confirmed - working on a fix now

**Comment by jshiplett** [comment] 2023-08-23 19:23
This is primarily a doc issue but the issue is being triggered by PlatformTools config:

$content = @"
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: $($regionObject.kubernetes.tanzuNamespace)
  namespace: $($regionObject.kubernetes.tanzuNamespace)
spec:
  topology:
    controlPlane:
      count: 3
      class: $($regionObject.kubernetes.class)
      storageClass: $($regionObject.kubernetes.storagePolicyName)
    workers:
      count: 3
      class: $($regionObject.kubernetes.class)
      storageClass: $($regionObject.kubernetes.storagePolicyName)
  distribution:
    version: v1.20 <------------------ <<<<<Here is the problem>>>>>
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["$($regionObject.kubernetes.cidrBlockServices)"]
      pods:
        cidrBlocks: ["$($regionObject.kubernetes.cidrBlockPods)"]
"@

**Comment by tenthirtyam** [comment] 2023-08-23 19:51
@Ashwini-Ravi - This needs to be addressed in the `VMware.PlatformTools` module.

**Closed by tenthirtyam** 2023-08-23 19:51 UTC
Labels: bug, needs-triage, vvs/dri
